apiVersion: v1
kind: Pod
metadata:
  name: stack-punto-3
  annotations:
    sample: 800-555-1212
  labels:
    app: punto-3
    version: v1
spec:
  containers:
   - name: aplicacion
     image: dpinta/aplicacion:v1
     ports:
        - containerPort: 8080
     env:
        - name: host
          value: localhost
        - name: port
          value: "3306"
   - name: bd   
     image: dpinta/bd-mysql
     ports:
        - containerPort: 3306
  restartPolicy: OnFailure
