apiVersion: v1
kind: Service
metadata:
  namespace: name1
  name: my-cip-service
spec:
  type: ClusterIP
  selector:
    app: database
    project: final
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306