apiVersion: v1
kind: Service
metadata:
  namespace: name1
  name: my-cip-app
spec:
  type: ClusterIP
  selector:
    app: aplicacion
    project: final
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080