apiVersion: v1
kind: Pod
metadata:
  namespace: name1
  name: db
  labels:
    app: database
    project: final
spec:
  containers:
   - name: db
     image: dpinta/bd-mysql
     ports:
        - containerPort: 3306
  restartPolicy: OnFailure
