apiVersion: v1
kind: Service
metadata:
  namespace: name2
  name: headless-service
spec:
  clusterIP: None 
  selector:
    app: sts-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306